name: Run Selenium Script

# 推上主線後自動運行
on:
  push:
    branches:
      - main  
jobs:
  run-selenium-script:
    runs-on: ubuntu-latest  # ubuntu

    steps:
    - name: Checkout Code  
      uses: actions/checkout@v2 
# 安裝python
    - name: Set up Python  
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9  
# 安裝套件
    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .
# 執行程式碼
    - name: Run Selenium Script  
      run: |
        python selenium_test.py
      working-directory: .