name: Run cicd Script

# 推上主線後自動運行
on:
  push:
    branches:
      - main  
# on:
#   schedule:
#     - cron: '0 * * * *'  # 每小時運行
jobs:
  run-cicd-script:
    runs-on: ubuntu-latest  # ubuntu

    services:
      redis:
        image: redis
        ports:
          - 8080:8080

    steps:
    - name: Checkout Code  
      uses: actions/checkout@v2 
# 安裝python
    - name: Set up Python  
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9  
# 安裝套件
    - name: Install Dependencies 
      run: |
        sudo apt update
        sudo apt install redis-server
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .
    - name: Start Redis Server
      run: |
        redis-cli ping
        echo "Redis is already running on port 8080."
      continue-on-error: true  # 如果 Redis 伺服器未運行，繼續執行下一步
#執行
    - name: Run cicd_test Script
      run: |
        python cicd_test.py
      working-directory: .
    - name: Stop Redis Server
      run: |
        echo "Redis will be stopped automatically."