name: Run Selenium Script

on:
  push:
    branches:
      - main  
jobs:
  run-selenium-script:
    runs-on: ubuntu-latest  

    steps:
    - name: Checkout Code  
      uses: actions/checkout@v2 

    - name: Set up Python  
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9  

    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .

    - name: Run Selenium Script  
      run: |
        python selenium_test.py
      working-directory: .