name: Run cicd Script

# 推上主線後自動運行
on:
  push:
    branches:
      - main  
# on:
#   schedule:
#     - cron: '0 * * * *'  # 每小時運行
jobs:
  run-cicd-script:
    runs-on: ubuntu-latest  # ubuntu

    services:
      redis:
        image: redis
        ports:
          - localhost:8080
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout Code  
      uses: actions/checkout@v2 
# 安裝python
    - name: Set up Python  
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9  
# 安裝套件
    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .
    - name: Start Redis Server
      run: |
        sudo systemctl start redis-service
      continue-on-error: true  # 如果 Redis 伺服器未運行，繼續執行下一步
#執行
    - name: Run cicd_test Script
      run: |
        python cicd_test.py
      working-directory: .
    - name: Stop Redis Server
      run: |
        sudo systemctl stop redis-service