name: Run cicd Script

#推上主線後自動運行
on:
  push:
    branches:
      - main  
# on:
#   schedule:
#     - cron: '* * * * 1'  # 每周一運行
jobs:
  run-cicd-script:
    runs-on: ubuntu-latest  # ubuntu
    env:
        GCP_KEY: ${{ secrets.GCP_KEY }}
        DB_HOST: '35.201.205.128'
        DB_USER: root
        DB_PASSWORD: 'd]a)Qf8=moJ"YiOU'
        DB_NAME: 'gitaction'
        DB_PORT: 3306
    services:
      redis:
        image: redis
        ports:
          - 6379:6379
    steps:
    - name: Checkout Code  
      uses: actions/checkout@v2 
# 安裝python
    - name: Set up Python  
      uses: actions/setup-python@v2 
      with:
        python-version: 3.9  
# 安裝套件
    - name: Install Dependencies 
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      working-directory: .

    - name: Start Redis Server
      run: |
        echo "Redis is already running on port 6379."
      continue-on-error: true  # 如果 Redis 伺服器未運行，繼續執行下一步
#執行
    - name: Run cicd_test Script
      run: |
        python cicd_test.py
      working-directory: .
    - name: Stop Redis Server
      run: |
        echo "Redis will be stopped automatically."